CREATE TABLE IF NOT EXISTS users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(100) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    City VARCHAR(100) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    PostalCode VARCHAR(100) NOT NULL,
    State VARCHAR(100) NOT NULL,
    Street VARCHAR(100) NOT NULL,
    UserType TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS items (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Category VARCHAR(100) NOT NULL,
    Gender VARCHAR(100) NOT NULL,
    Quantity TINYINT NOT NULL,
    Size VARCHAR(100) NOT NULL,
    Status VARCHAR(100) NOT NULL,
    ShelterID INTEGER NOT NULL,
    FOREIGN KEY(ShelterID) REFERENCES users(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS userSessions (
    SessionKey VARCHAR(50) PRIMARY KEY,
    UserID INTEGER NOT NULL,
    UserType TINYINT NOT NULL,
    LoginTime BIGINT NOT NULL,
    LastSeenTime BIGINT NOT NULL,
    FOREIGN KEY(UserID) REFERENCES users(ID) ON DELETE CASCADE
);
